# Numpy 

In [8]:
import numpy as np

In [21]:
nums=np.array(100)

In [22]:
print(nums)

100


In [23]:
nums*2

200

In [24]:
num=np.arange(100)

In [19]:
print(num)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [20]:
num*2

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102,
       104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128,
       130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154,
       156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180,
       182, 184, 186, 188, 190, 192, 194, 196, 198])

In [25]:
np.array([1,2,3,4,5,6])

array([1, 2, 3, 4, 5, 6])

In [26]:
np.array([1,2,3.14,3.24,5,6,67.8])

array([ 1.  ,  2.  ,  3.14,  3.24,  5.  ,  6.  , 67.8 ])

In [27]:
np.array([True,False,23])

array([ 1,  0, 23])

In [31]:
arr3=np.array([1,2,3,4,'string'])
arr3

array(['1', '2', '3', '4', 'string'], dtype='<U11')

In [29]:
arr3.dtype

dtype('<U11')

In [32]:
arr4=np.array([True,False,True])
arr4

array([ True, False,  True])

In [33]:
arr4.dtype

dtype('bool')

In [34]:
arr6=np.array([1,2,3,4,5,6,7,8,8])

In [35]:
arr6.size

9

In [36]:
arr7=np.array([1,2,3,4])

In [37]:
arr7

array([1, 2, 3, 4])

In [38]:
arr7.size

4

In [39]:
arr7.dtype

dtype('int32')

In [40]:
arr7.ndim

1

In [42]:
arr9= np.array([[1,2,3],[1,2,3]]) #array of array 

In [43]:
arr9

array([[1, 2, 3],
       [1, 2, 3]])

In [44]:
arr9.ndim # 2-dimentional array

2

In [47]:
arr0= np.array([[[1,2,3],[4,5,6]],[[1,2,4],[4,5,7]]])

In [48]:
arr0

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 4],
        [4, 5, 7]]])

In [50]:
arr0.size

12

In [51]:
arr0.ndim

3

In [52]:
arr0.dtype

dtype('int32')

In [81]:
arr1=np.array([[[1,2,4],[2,3,7]],[[2,3,8],[3,3,8]],[[4,5,8],[5,7,3]],[[6,8,4],[6,8,3]]])

In [82]:
arr1

array([[[1, 2, 4],
        [2, 3, 7]],

       [[2, 3, 8],
        [3, 3, 8]],

       [[4, 5, 8],
        [5, 7, 3]],

       [[6, 8, 4],
        [6, 8, 3]]])

In [83]:
arr1.size

24

In [84]:
arr1.ndim

3

In [85]:
arr1.dtype

dtype('int32')

In [86]:
arr1.shape

(4, 2, 3)

In [87]:
arro=np.array([[1,2,3,4,5],[1,2,3,4,5]])

In [88]:
arro.shape

(2, 5)

In [89]:
arro.size

10

In [97]:
arr11=np.array([[[1,2,3,4],[3,4,5,6]],[[1,2,3,4],[3,4,6,7.0]]])

In [98]:
print(arr11.shape)
print(arr11.ndim)
print(arr11.size)
print(arr11.dtype)

(2, 2, 4)
3
16
float64


In [99]:
arr12=np.array([[[1,2,3,4]],[[1,2,3,4],[3,4,6,7.0]]])

<ipython-input-99-6094779b3750>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr12=np.array([[[1,2,3,4]],[[1,2,3,4],[3,4,6,7.0]]])


In [100]:
print(arr12.shape)
print(arr12.ndim)
print(arr12.size)
print(arr12.dtype)

(2,)
1
2
object


In [101]:
arr12

array([list([[1, 2, 3, 4]]), list([[1, 2, 3, 4], [3, 4, 6, 7.0]])],
      dtype=object)

# arange

In [102]:
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [103]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [104]:
np.arange(100,0,-1)

array([100,  99,  98,  97,  96,  95,  94,  93,  92,  91,  90,  89,  88,
        87,  86,  85,  84,  83,  82,  81,  80,  79,  78,  77,  76,  75,
        74,  73,  72,  71,  70,  69,  68,  67,  66,  65,  64,  63,  62,
        61,  60,  59,  58,  57,  56,  55,  54,  53,  52,  51,  50,  49,
        48,  47,  46,  45,  44,  43,  42,  41,  40,  39,  38,  37,  36,
        35,  34,  33,  32,  31,  30,  29,  28,  27,  26,  25,  24,  23,
        22,  21,  20,  19,  18,  17,  16,  15,  14,  13,  12,  11,  10,
         9,   8,   7,   6,   5,   4,   3,   2,   1])

# Reshape

In [105]:
arr16=np.arange(100)

In [108]:
arr16.reshape(10,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [112]:
arr50=np.arange(50)
arr50
arr50.reshape(5,5,2)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [113]:
arr50.reshape(5,5,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]],

       [[40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49]]])

In [114]:
arr20=np.arange(120).reshape(12,10)

In [128]:
arr20

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99],
       [100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119]])

In [129]:
arr20.ravel()

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119])

# Zeros

In [117]:
np.zeros(100)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [118]:
np.zeros(130).reshape(13,10)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [130]:
np.zeros(50).reshape(10,5)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])