# Floor and Ceil

In [1]:
import numpy as np
arr1=np.array([3.14,5.5,6.34,7.6])
arr1

array([3.14, 5.5 , 6.34, 7.6 ])

In [4]:
np.floor(arr1)

array([3., 5., 6., 7.])

In [5]:
np.ceil(arr1)

array([4., 6., 7., 8.])

In [6]:
np.round(arr1)

array([3., 6., 6., 8.])

In [7]:
arr2=np.array([2.2,3.6,4.2])
arr2

array([2.2, 3.6, 4.2])

In [8]:
print(np.floor(arr2))
print(np.ceil(arr2))
print(np.round(arr2))

[2. 3. 4.]
[3. 4. 5.]
[2. 4. 4.]


# Stacking 

In [10]:
arr3=np.arange(10).reshape(2,5)
arr3

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [11]:
arr4=np.arange(20).reshape(4,5)
arr4

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [15]:
np.vstack((arr3,arr4))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [27]:
np.hstack((arr3,arr4)) #all the input array dimensions for the concatenation axis must match exactly, 
                       #but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 4

In [17]:
arr5=np.arange(20).reshape(4,5)
arr5

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [24]:
arr6=np.zeros(24).reshape(4,6)
arr6

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [25]:
np.hstack((arr5,arr6))

array([[ 0.,  1.,  2.,  3.,  4.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 5.,  6.,  7.,  8.,  9.,  0.,  0.,  0.,  0.,  0.,  0.],
       [10., 11., 12., 13., 14.,  0.,  0.,  0.,  0.,  0.,  0.],
       [15., 16., 17., 18., 19.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [26]:
np.hstack((arr5,arr6)).astype(int)

array([[ 0,  1,  2,  3,  4,  0,  0,  0,  0,  0,  0],
       [ 5,  6,  7,  8,  9,  0,  0,  0,  0,  0,  0],
       [10, 11, 12, 13, 14,  0,  0,  0,  0,  0,  0],
       [15, 16, 17, 18, 19,  0,  0,  0,  0,  0,  0]])

# Split

In [2]:
import numpy as np

In [5]:
arr7= np.arange(100).reshape(10,10)

In [4]:
arr7

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [7]:
np.vsplit(arr7,5)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]]),
 array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]]),
 array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]]),
 array([[60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79]]),
 array([[80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])]

In [9]:
np.hsplit(arr7,5)

[array([[ 0,  1],
        [10, 11],
        [20, 21],
        [30, 31],
        [40, 41],
        [50, 51],
        [60, 61],
        [70, 71],
        [80, 81],
        [90, 91]]),
 array([[ 2,  3],
        [12, 13],
        [22, 23],
        [32, 33],
        [42, 43],
        [52, 53],
        [62, 63],
        [72, 73],
        [82, 83],
        [92, 93]]),
 array([[ 4,  5],
        [14, 15],
        [24, 25],
        [34, 35],
        [44, 45],
        [54, 55],
        [64, 65],
        [74, 75],
        [84, 85],
        [94, 95]]),
 array([[ 6,  7],
        [16, 17],
        [26, 27],
        [36, 37],
        [46, 47],
        [56, 57],
        [66, 67],
        [76, 77],
        [86, 87],
        [96, 97]]),
 array([[ 8,  9],
        [18, 19],
        [28, 29],
        [38, 39],
        [48, 49],
        [58, 59],
        [68, 69],
        [78, 79],
        [88, 89],
        [98, 99]])]

In [10]:
res2=np.hsplit(arr7,5)

In [11]:
res2[1]

array([[ 2,  3],
       [12, 13],
       [22, 23],
       [32, 33],
       [42, 43],
       [52, 53],
       [62, 63],
       [72, 73],
       [82, 83],
       [92, 93]])

# Slicing 

In [16]:
Sentence='Today was a good day'

In [17]:
Sentence[6:9]

'was'

In [18]:
Sentence[:5]

'Today'

In [21]:
Sentence[3:]

'ay was a good day'

In [27]:
Sentence[12:16]

'good'

# Pandas


In [31]:
import pandas as pd

In [34]:
ser1=pd.Series([3,4,5,6,7,8,9,10,3.14])
ser1

0     3.00
1     4.00
2     5.00
3     6.00
4     7.00
5     8.00
6     9.00
7    10.00
8     3.14
dtype: float64

In [47]:
ser1[0:5] # 5 excluded

0    3.0
1    4.0
2    5.0
3    6.0
4    7.0
dtype: float64

In [37]:
ser2=pd.Series([3,4,5,6,7,8,9,10,3.14], index=['r1','r2','r3','r4','r5','r6','r7','r8','r9'])
ser2

r1     3.00
r2     4.00
r3     5.00
r4     6.00
r5     7.00
r6     8.00
r7     9.00
r8    10.00
r9     3.14
dtype: float64

In [46]:
ser2['r1':'r4'] # r4 included

r1    3.0
r2    4.0
r3    5.0
r4    6.0
dtype: float64

In [40]:
ser3=pd.Series([1,2,3,4,5,6,7,8,9,0], index=['a','b','c','d','e','f','g','h','i','j'])

In [41]:
ser3

a    1
b    2
c    3
d    4
e    5
f    6
g    7
h    8
i    9
j    0
dtype: int64

In [43]:
ser3['b':'g']

b    2
c    3
d    4
e    5
f    6
g    7
dtype: int64

In [51]:
ser4=pd.Series([4,3,2,1], index=[1,2,3,4])

In [53]:
ser4[2:4]

3    2
4    1
dtype: int64

In [57]:
ser5=pd.Series(np.arange(10))

In [58]:
ser5

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int32

In [59]:
ser6=pd.Series(np.zeros(10))

In [3]:
ser6

NameError: name 'ser6' is not defined

In [7]:
def _sum(arr): 
    sum=0
    for i in arr:
        sum = sum + i
    return(sum)

In [8]:
arr=[] 
arr = [12, 3, 4, 15] 
n = len(arr) 
ans = _sum(arr) 
print ('Sum of the array is ', ans)

Sum of the array is  34


In [9]:
arr.max()

AttributeError: 'list' object has no attribute 'max'

In [12]:
arr= np.arange(28).reshape(2,14)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27]])

In [11]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27]])

In [13]:
arr= np.arange(40,100,2)
arr

array([40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72,
       74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [14]:
arr = [[14, 17, 12, 33, 44],   
       [15, 6, 27, 8, 19],  
       [23, 2, 54, 1, 4,]] 

In [15]:
row=np.sum(arr, axis = 0) 
column=np.sum(arr, axis = 1)
  
total=row+column

ValueError: operands could not be broadcast together with shapes (5,) (3,) 

In [19]:
np.zeros(5, dtype='int')

array([0, 0, 0, 0, 0])

In [22]:
np.arange(1,20).reshape(5,4)

ValueError: cannot reshape array of size 19 into shape (5,4)

In [23]:
np.array(2)

array(2)