In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('iris.csv',index_col='Id')

In [3]:
df

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
Id                                                                    
1              5.1           3.5            1.4           0.2        0
2              4.9           3.0            1.4           0.2        0
3              4.7           3.2            1.3           0.2        0
4              4.6           3.1            1.5           0.2        0
5              5.0           3.6            1.4           0.2        0
..             ...           ...            ...           ...      ...
146            6.7           3.0            5.2           2.3        2
147            6.3           2.5            5.0           1.9        2
148            6.5           3.0            5.2           2.0        2
149            6.2           3.4            5.4           2.3        2
150            5.9           3.0            5.1           1.8        2

[150 rows x 5 columns]

In [4]:
df.loc[df.Species==0, 'Species'] = 'Setosa'
df.loc[df.Species==1, 'Species'] = 'Versicolor'
df.loc[df.Species==2, 'Species'] = 'Virginica'

In [5]:
df.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm Species
Id                                                                  
1             5.1           3.5            1.4           0.2  Setosa
2             4.9           3.0            1.4           0.2  Setosa
3             4.7           3.2            1.3           0.2  Setosa
4             4.6           3.1            1.5           0.2  Setosa
5             5.0           3.6            1.4           0.2  Setosa

# Build and Evaluate a model

In [6]:
# Importing metrics for evaluation
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [7]:
# Seperating the data into dependent and independent variables
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 15)

In [9]:
# LogisticRegression
from sklearn.linear_model import LogisticRegression
LR_classifier = LogisticRegression()
LR_classifier.fit(X_train, y_train)

y_pred = LR_classifier.predict(X_test)

# Summary of the predictions made by the classifier
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
# Accuracy score
from sklearn.metrics import accuracy_score
print('accuracy is',accuracy_score(y_pred,y_test))

              precision    recall  f1-score   support

      Setosa       1.00      1.00      1.00         8
  Versicolor       1.00      1.00      1.00        13
   Virginica       1.00      1.00      1.00         9

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

[[ 8  0  0]
 [ 0 13  0]
 [ 0  0  9]]
accuracy is 1.0


C:\Users\Shayeda\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [10]:
# Naive Bayes
from sklearn.naive_bayes import GaussianNB
NB_classifier = GaussianNB()
NB_classifier.fit(X_train, y_train)

y_pred = NB_classifier.predict(X_test)

# Summary of the predictions made by the classifier
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
# Accuracy score
from sklearn.metrics import accuracy_score
print('accuracy is',accuracy_score(y_pred,y_test))

              precision    recall  f1-score   support

      Setosa       1.00      1.00      1.00         8
  Versicolor       1.00      1.00      1.00        13
   Virginica       1.00      1.00      1.00         9

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

[[ 8  0  0]
 [ 0 13  0]
 [ 0  0  9]]
accuracy is 1.0


In [11]:
# Support Vector Machine's 
from sklearn.svm import SVC

SVM_classifier = SVC()
SVM_classifier.fit(X_train, y_train)

y_pred = SVM_classifier.predict(X_test)

# Summary of the predictions made by the classifier
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
# Accuracy score
from sklearn.metrics import accuracy_score
print('accuracy is',accuracy_score(y_pred,y_test))

              precision    recall  f1-score   support

      Setosa       1.00      1.00      1.00         8
  Versicolor       1.00      1.00      1.00        13
   Virginica       1.00      1.00      1.00         9

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

[[ 8  0  0]
 [ 0 13  0]
 [ 0  0  9]]
accuracy is 1.0


In [12]:
# K-Nearest Neighbours
from sklearn.neighbors import KNeighborsClassifier

KNN_classifier = KNeighborsClassifier(n_neighbors=8)
KNN_classifier.fit(X_train, y_train)

y_pred = KNN_classifier.predict(X_test)

# Summary of the predictions made by the classifier
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
# Accuracy score
from sklearn.metrics import accuracy_score
print('accuracy is',accuracy_score(y_pred,y_test))

              precision    recall  f1-score   support

      Setosa       1.00      1.00      1.00         8
  Versicolor       1.00      1.00      1.00        13
   Virginica       1.00      1.00      1.00         9

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

[[ 8  0  0]
 [ 0 13  0]
 [ 0  0  9]]
accuracy is 1.0


In [13]:
# Decision Tree's
from sklearn.tree import DecisionTreeClassifier

DT_classifier = DecisionTreeClassifier()

DT_classifier.fit(X_train, y_train)

y_pred = DT_classifier.predict(X_test)

# Summary of the predictions made by the classifier
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
# Accuracy score
from sklearn.metrics import accuracy_score
print('accuracy is',accuracy_score(y_pred,y_test))

              precision    recall  f1-score   support

      Setosa       1.00      1.00      1.00         8
  Versicolor       0.93      1.00      0.96        13
   Virginica       1.00      0.89      0.94         9

    accuracy                           0.97        30
   macro avg       0.98      0.96      0.97        30
weighted avg       0.97      0.97      0.97        30

[[ 8  0  0]
 [ 0 13  0]
 [ 0  1  8]]
accuracy is 0.9666666666666667


In [15]:
import joblib
joblib.dump(KNN_classifier,'KNN_deployment_model.pkl')

['KNN_deployment_model.pkl']

In [16]:
import joblib
joblib.dump(DT_classifier,'DT_deployment_model.pkl')

['DT_deployment_model.pkl']

In [17]:
import joblib
joblib.dump(SVM_classifier,'SVM_deployment_model.pkl')

['SVM_deployment_model.pkl']

In [18]:
import joblib
joblib.dump(NB_classifier,'NB_deployment_model.pkl')

['NB_deployment_model.pkl']

In [19]:
import joblib
joblib.dump(LR_classifier,'LR_deployment_model.pkl')

['LR_deployment_model.pkl']